### ISSUE TITLE
SST Error: ReferenceError: __dirname is not defined

### ISSUE THREAD

**Issue by emmamoinat** [jumper-de/cdk-auth0#7]
## Error of `ReferenceError: __dirname is not defined`

When attempting to deploy an Auth0 trigger and action with `sst` I am receiving the error `ReferenceError: __dirname is not defined`

Code:
```
    const auth0Secret = Secret.fromSecretNameV2(
      stack,
      "Auth0SecretMachineToMachineConfig",
      "my-machine-to-machine-secret-name",
    );

    new Trigger(stack, "Auth0PostLoginTrigger", {
      apiSecret: auth0Secret,
      id: "post-login",
      actions: [
        new Action(stack, "Auth0AugmentClaimAction", {
          apiSecret: auth0Secret,
          name: "AugmentClaims",
          runtime: "node18",
          supportedTriggers: [{ id: "post-login", version: "v3" }],
          code: `
            exports.onExecutePostLogin = async (event, api) => {
              api.idToken.setCustomClaim("example", "test123");
              api.accessToken.setCustomClaim("example", "test123");
            }
          `,
        }),
      ],
    });
```

### Your environment
- "@flit/cdk-auth0": "1.9.3"
- "sst": "2.38.7"

### Steps to reproduce
1. Add the above code to an sst stack
2. run `sst dev`
3. Receive error: 
```
ReferenceError: __dirname is not defined
       at new Provider 
       at Provider.getOrCreate
       at new Action
```

### Expected behaviour
Should deploy an action to referenced auth0 account

### Actual behaviour
Not compiling

### Likely fix

Something along the lines of 
https://www.geeksforgeeks.org/how-to-fix-referenceerror-dirname-is-not-defined-in-es-module-scope-in-javascript/

**Comment by p-mercury** [comment]
That should be a quick fix, I'll take a look later today and let you know once a new version is available.

**Comment by p-mercury** [comment]
It actually seems that fixing this issue on my side is not possible!

`CDK` packages are required to use `JSII` which only supports `CJS`, and if I include an alternative using `@ts-ignore` it still throws an error as the module is not `ESM`.

I would suggest you try using a bundler that automatically adapts `CJS` packages to work in your `ESM` environment or you manually inject `__dirname = import.meta.dirname;` to the top of your bundle before it runs.

If you figure out a way to fix this on the side of the package you can open a PR 👍

**Comment by emmamoinat** [comment]
> It actually seems that fixing this issue on my side is not possible!
> 
> `CDK` packages are required to use `JSII` which only supports `CJS`, and if I include an alternative using `@ts-ignore` it still throws an error as the module is not `ESM`.
> 
> I would suggest you try using a bundler that automatically adapts `CJS` packages to work in your `ESM` environment or you manually inject `__dirname = import.meta.dirname;` to the top of your bundle before it runs.
> 
> If you figure out a way to fix this on the side of the package you can open a PR 👍

Yeah was worried this might be the case - I will have a play around and see but not sure if `sst` will have a workaround for this. Injecting the `__dirname` could work - I did try that already but didn't spend long on it until I got a response from yourself.

I will let you know if I manage
